version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - .env

  api:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure

volumes:
  progresDB:
